name: AutoSync Actions
on:
  schedule:
    - cron: 30 */24 * * *
  workflow_dispatch:
jobs:
  rclone-syncProcess:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Installing rclone
      run: curl https://rclone.org/install.sh | sudo bash
    - name: Inject rclone.conf
      run: |
        mkdir -p ~/.config/rclone/
        cat >  ~/.config/rclone/rclone.conf  << EOF
        ${{ secrets.backup }}
        EOF
    - name: Rclone Sync
      run: |
        rclone sync 'COPY:' 'PASTE:' --drive-server-side-across-configs -P
